# Project information
site_name: 'Notes'
site_description: ''
site_author: 'Wes Roach'
site_url: 'http://mkdocs.wesroach.com'

nav:
  - Home: index.md
  - Python:
    - 10Apps: python/10apps.md
  - Pandas: pandas/pandas.md
  - Dask: dask/dask.md
  - Kubernetes:
    - EDx: kubernetes/edx.md
  - SAS: sas/sas.md
  - Networking:
    - OSI: networking/osi.md
    - ARP: networking/arp.md
    - Subnetting: networking/subnetting.md
  - License: license.md

# Repository
repo_name: 'WesRoach/mkdocs-wesroach'
repo_url: 'https://github.com/WesRoach/mkdocs-wesroach'

# Copyright
copyright: 'Copyright &copy; 2021 Wes Roach'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false
use_directory_urls: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/WesRoach'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/WesRoach'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/wes-roach/'
  search:
    tokenizer: '[\s\-\.]+'


# Google Analytics
google_analytics:
  - 'UA-113461484-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
