# Project information
site_name: 'Notes'
site_description: ''
site_author: 'Wes Roach'
site_url: 'http://mkdocs.wesroach.com'

pages:
  - Home: index.md
  - About: about.md
  - SAS: sas-notes.md
  - pandas: pandas/pandas-notes.md
  - License: license.md

# Repository
repo_name: 'WesRoach/mkdocs-wesroach'
repo_url: 'https://github.com/WesRoach/mkdocs-wesroach'

# Copyright
copyright: 'Copyright &copy; 2018 Wes Roach'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/WesRoach'
    - type: 'twitter'
      link: 'https://twitter.com/WesRoach'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/wes-roach/'
  search:
    tokenizer: '[\s\-\.]+'
  disqus: 'mkdocs-material' # site_url must be set

# Google Analytics
google_analytics:
  - 'UA-113461484-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde